const A = window.ATLAS;
A.dynamicNews = [];
const allNews = () => {
  const merged = [...A.dynamicNews, ...A.seedNews];
  const seen = new Set();
  return merged.filter(x => { const k = x.url || x.title; if (seen.has(k)) return false; seen.add(k); return true; });
};
const app = document.getElementById('app');
const qs = () => new URLSearchParams(location.search);
const state = {domain: qs().get('domain') || 'home', view: qs().get('view') || 'today'};
const subviews = ['overview','knowledge','case','research','news','companies','market'];
const labels = {overview:'领域总览',knowledge:'知识地图',case:'案例实验室',research:'科研进展',news:'产业动态',companies:'企业观察',market:'市场洞察'};
const domainName = d => d==='home'?'今日':A.domains[d]?.name || d;
const esc = s => String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
function nav(domain, view='overview', extra={}){
  const u = new URL(location.href); u.search=''; u.searchParams.set('domain',domain);u.searchParams.set('view',view);
  Object.entries(extra).forEach(([k,v])=>u.searchParams.set(k,v)); history.pushState({},'',u); state.domain=domain;state.view=view;render();
}
function setActive(){document.querySelectorAll('.domain-nav button').forEach(b=>b.classList.toggle('active',b.dataset.domain===state.domain));}
function fmt(n,d=0){return Number(n).toLocaleString('zh-CN',{maximumFractionDigits:d});}
function todayPlan(){const day=Math.floor(Date.now()/86400000);return A.studyPlan[day%A.studyPlan.length]}
function render(){state.domain=qs().get('domain')||state.domain||'home';state.view=qs().get('view')||state.view||'today';setActive();app.innerHTML=state.domain==='home'?renderHome():renderDomain(state.domain,state.view);bindPage();document.getElementById('footerUpdated').textContent=`内容核验：${A.meta.verifiedAt}`;window.scrollTo({top:0,behavior:'instant'});}
function hero({eyebrow,title,desc,side}){return `<section class="hero"><div class="hero-main"><div class="eyebrow">${esc(eyebrow)}</div><h1>${title}</h1><p>${desc}</p><div class="hero-actions"><button class="btn primary" data-go="aidc,knowledge">进入知识地图</button><button class="btn" data-go="aidc,case">打开 100MW 案例实验室</button></div></div><aside class="hero-side">${side}</aside></section>`}
function renderHome(){const p=todayPlan();const d=A.domains[p.domain];const latest=[...allNews()].sort((a,b)=>b.published_at.localeCompare(a.published_at)).slice(0,4);return `${hero({eyebrow:'TODAY / TECHNOLOGY ATLAS',title:'每天系统学习，<br>每天观察变化。',desc:'把 AIDC、具身智能与机器学习连接成一张可持续更新的技术地图：知识有体系，案例能推演，变化有来源。',side:`<div class="status-line"><span class="status-dot"></span>每日自动更新机制已纳入工程</div><div><div class="big-number">3</div><div class="metric-label">核心技术域</div></div><div class="tiny">AIDC · 具身智能 · 机器学习<br>统一知识地图与动态情报结构</div>`})}
<section class="today-grid"><div class="card learning-card"><div class="section-kicker">TODAY'S STUDY · ${p.minutes} MIN</div><h2>${esc(p.title)}</h2><p>${esc(d.name)} · 今日学习会自动关联到对应知识章节与案例节点。</p><div class="step-list">${p.path.map((x,i)=>`<div class="step"><b>${String(i+1).padStart(2,'0')}</b><span>${esc(x)}</span></div>`).join('')}</div><div class="hero-actions"><button class="btn primary" data-article="${p.article}">开始今日学习</button><button class="btn" data-go="${p.domain},knowledge">查看完整知识地图</button></div></div><div class="card"><div class="section-kicker">TODAY'S CHANGES</div><div class="signal-list">${latest.map(n=>`<a class="signal" href="${n.url}" target="_blank" rel="noreferrer"><span class="signal-icon">↗</span><span><strong>${esc(n.title)}</strong><p>${esc(n.what_changed)}</p></span><time>${n.published_at.slice(5)}</time></a>`).join('')}</div></div></section>
${renderCrossDomainMap()}
${renderMarketSection()}
${renderNewsSection(allNews(),'本期重点变化')}`}
function renderCrossDomainMap(){return `<section class="section"><div class="section-head"><div><div class="section-kicker">KNOWLEDGE GRAPH</div><h2>三大领域，不是三座孤岛</h2><p>从底层基础设施一路连接到模型、智能体与机器人行动。</p></div></div><div class="architecture panel">${['电力 / 制冷','GPU / 网络','训练 / 推理','Agent Runtime','World Model','Robot Action'].map(x=>`<div class="arch-node">${x}</div>`).join('')}</div></section>`}
function subnav(d,v){return `<nav class="subnav">${subviews.map(x=>`<button class="${x===v?'active':''}" data-go="${d},${x}">${labels[x]}</button>`).join('')}</nav>`}
function renderDomain(d,v){const x=A.domains[d];return `${hero({eyebrow:x.eyebrow,title:x.name,desc:x.intro,side:`<div class="status-line"><span class="status-dot"></span>${esc(x.accent)}</div><div><div class="big-number">${x.knowledge.length}</div><div class="metric-label">核心知识专题</div></div><div class="tiny">目录、动态标签、企业观察与市场洞察使用统一结构。</div>`})}${subnav(d,v)}${renderView(d,v)}`}
function renderView(d,v){if(v==='knowledge'||v==='overview')return renderKnowledge(d,v==='overview');if(v==='case')return renderCase(d);if(v==='market')return d==='aidc'?renderMarketSection(true):renderPlaceholder('市场数据正在扩充','该领域的数据页已保留统一结构。');if(v==='companies')return renderCompanies(d);if(v==='news')return renderNewsSection(allNews().filter(n=>n.domain===d&&n.category==='产业动态'),'产业动态');if(v==='research')return renderNewsSection(allNews().filter(n=>n.domain===d&&n.category==='科研进展'),'科研进展');return renderKnowledge(d)}
function renderKnowledge(d,overview=false){const dom=A.domains[d];return `<section class="section"><div class="section-head"><div><div class="section-kicker">${overview?'DOMAIN OVERVIEW':'KNOWLEDGE MAP'}</div><h2>${overview?'从系统看整个领域':'按依赖关系系统学习'}</h2><p>每个节点继续展开为原理、架构、参数、公式、工程实践与最新进展。</p></div></div>${d==='aidc'?`<div class="architecture panel">${['业务负载','园区 / 电力','机柜 / GPU','网络 / 存储','调度 / 运维','成本 / 能效'].map(x=>`<div class="arch-node">${x}</div>`).join('')}</div>`:''}<div class="knowledge-map section">${dom.knowledge.map(k=>`<article class="knowledge-node" data-knowledge="${k[3]}"><div class="num">${k[0]}</div><h3>${k[1]}</h3><p>${k[2]}</p></article>`).join('')}</div></section>`}
function renderArticle(id){const a=A.articles[id];if(!a)return renderPlaceholder('专题建设中','该知识节点会继续补充。');return `<article class="article"><div class="section-kicker">${esc(domainName(a.domain))} / ${esc(a.category)}</div><h1>${esc(a.title)}</h1><p>${esc(a.lead)}</p>${a.domain==='aidc'&&id==='cooling'?`<div class="architecture panel section">${['GPU/CPU','Cold Plate','CDU','Facility Water','Chiller','Cooling Tower'].map(x=>`<div class="arch-node">${x}</div>`).join('')}</div>`:''}${a.domain==='embodied'?`<div class="architecture panel section">${['Observation','Latent State','World Model','Planning','Policy','Action'].map(x=>`<div class="arch-node">${x}</div>`).join('')}</div>`:''}${a.sections.map(s=>`<h2>${esc(s[0])}</h2><p>${esc(s[1])}</p>`).join('')}<h2>核心关系</h2><pre class="formula">${esc(a.formula)}</pre><div class="callout">在 Technology Atlas 中，这一知识不会孤立存在：它会与案例实验室参数、产业动态和企业技术路线互相链接。</div><div class="source-list">${a.sources.map(s=>`<a class="source-link" href="${s[1]}" target="_blank" rel="noreferrer">来源 · ${esc(s[0])} ↗</a>`).join('')}</div><div class="hero-actions"><button class="btn" data-go="${a.domain},knowledge">返回知识地图</button>${a.domain==='aidc'?`<button class="btn primary" data-go="aidc,case">在案例实验室中理解</button>`:''}</div></article>`}
function renderCase(d){if(d!=='aidc')return renderPlaceholder('案例实验室正在扩展',d==='embodied'?'后续将加入机器人任务与世界模型闭环实验。':'后续将加入推理服务与 Agent Runtime 实验。');return `<section class="section"><div class="section-head"><div><div class="section-kicker">CASE LAB / 100MW AI FACTORY</div><h2>把整座 AI Factory 当成一个可计算系统</h2><p>调整参数，观察 IT、设施功率、机柜、制冷、CDU 和年耗电如何联动。</p></div></div><div class="lab"><div class="card controls"><div class="control"><label><span>IT Load</span><b id="itLoadV">100 MW</b></label><input id="itLoad" type="range" min="20" max="300" step="5" value="100"></div><div class="control"><label><span>PUE</span><b id="pueV">1.18</b></label><input id="pue" type="range" min="1.05" max="1.50" step="0.01" value="1.18"></div><div class="control"><label><span>单柜功率</span><b id="rackPowerV">140 kW</b></label><input id="rackPower" type="range" min="40" max="250" step="5" value="140"></div><div class="control"><label><span>CDU 单元能力</span><b id="cduPowerV">1.2 MW</b></label><input id="cduPower" type="range" min="0.4" max="2.5" step="0.1" value="1.2"></div><div class="control"><label><span>液冷供回液温差 ΔT</span><b id="deltaTV">10 ℃</b></label><input id="deltaT" type="range" min="5" max="20" step="1" value="10"></div><div class="control"><label><span>冗余</span></label><select id="redundancy"><option value="1.08">N+1（示意）</option><option value="1.15">2N 局部冗余（示意）</option><option value="1.25">高冗余（示意）</option></select></div></div><div class="card lab-output"><div class="metric-grid"><div class="metric-box"><strong id="facilityLoad">118 MW</strong><span>Facility Load</span></div><div class="metric-box"><strong id="rackCount">715</strong><span>计算机柜（估算）</span></div><div class="metric-box"><strong id="cduCount">91</strong><span>CDU 单元（含冗余）</span></div><div class="metric-box"><strong id="annualEnergy">1.03 TWh</strong><span>设施年耗电（满载示意）</span></div></div><div class="architecture panel section">${['Grid','UPS / 800VDC','Rack GPU','CDU','Facility Water','Outdoor Heat Rejection'].map(x=>`<div class="arch-node">${x}</div>`).join('')}</div><h3>故障实验</h3><div class="faults">${['CDU 故障','UPS 故障','交换机拥塞','GPU Hotspot','冷却流量不足'].map(x=>`<button class="fault-btn" data-fault="${x}">${x}</button>`).join('')}</div><div id="faultPanel" class="fault-panel"><b>正常状态</b><p class="tiny">选择一个故障，观察物理指标、监控告警和业务影响如何传导。</p></div><div class="callout">这是工程估算器，不替代正式设计。冗余比例、CDU 能力、供回水参数等均需结合设备规格和现场条件复核。</div></div></div></section>`}
function renderMarketSection(standalone=false){const m=A.market.aidc;const values=m.points.map(p=>p.value);const max=Math.max(...values)*1.08;const w=760,h=230,pad=36;const pts=m.points.map((p,i)=>({x:pad+i*((w-2*pad)/(m.points.length-1)),y:h-pad-(p.value/max)*(h-2*pad),...p}));const poly=pts.map(p=>`${p.x},${p.y}`).join(' ');return `<section class="section"><div class="section-head"><div><div class="section-kicker">MARKET LENS / SOURCE-BACKED</div><h2>${m.title}</h2><p>${m.unit} · ${m.source}</p></div><a class="btn" href="${m.sourceUrl}" target="_blank" rel="noreferrer">原始来源 ↗</a></div><div class="panel chart-wrap"><svg class="chart-svg" viewBox="0 0 ${w} ${h}" role="img" aria-label="${m.title}"><defs><linearGradient id="areaGradient" x1="0" y1="0" x2="0" y2="1"><stop offset="0" stop-color="currentColor"/><stop offset="1" stop-color="currentColor" stop-opacity="0"/></linearGradient></defs>${[0,.25,.5,.75,1].map(t=>{const y=pad+(h-2*pad)*t;return `<line class="chart-grid" x1="${pad}" y1="${y}" x2="${w-pad}" y2="${y}"/>`}).join('')}<polyline class="chart-line" points="${poly}"/>${pts.map(p=>`<circle class="chart-dot" cx="${p.x}" cy="${p.y}" r="4"/><text class="chart-value" x="${p.x}" y="${p.y-10}" text-anchor="middle">${p.value}</text><text class="chart-label" x="${p.x}" y="${h-10}" text-anchor="middle">${p.label}</text>`).join('')}</svg></div><div class="callout">${m.note}</div></section>`}
function renderNewsSection(items,title){return `<section class="section"><div class="section-head"><div><div class="section-kicker">INTELLIGENCE FEED</div><h2>${title}</h2><p>统一字段：领域 / 类别 / 技术 / 企业 / 发布时间 / 核验时间 / 变化 / 影响 / 来源。</p></div></div><div class="news-list">${items.length?items.map(n=>`<article class="news-item"><div><div class="news-domain">${domainName(n.domain)}</div><div class="meta-row"><span class="tag">${esc(n.category)}</span><span class="tag">${esc(n.technology)}</span></div></div><div><h3>${esc(n.title)}</h3><p><b>变化：</b>${esc(n.what_changed)} <b>为什么重要：</b>${esc(n.why_it_matters)}</p><div class="meta-row"><a class="source-link" href="${n.url}" target="_blank" rel="noreferrer">${esc(n.source)} ↗</a>${n.related_knowledge?`<button class="chip" data-article="${n.related_knowledge}">关联知识</button>`:''}</div></div><div class="news-time">发布 ${n.published_at}<br>核验 ${n.verified_at}</div></article>`).join(''):`<div class="empty">今日暂无新的高质量条目。</div>`}</div></section>`}
function renderCompanies(d){const items=A.companies.filter(c=>c.domain.includes(d));return `<section class="section"><div class="section-head"><div><div class="section-kicker">COMPANY WATCH</div><h2>企业技术路线观察</h2><p>只跟踪与技术路线、产品架构和产业链变化直接相关的信息。</p></div></div><div class="grid cols-3">${items.map(c=>`<article class="card company-card"><div class="logo">${c.name.slice(0,2)}</div><h3>${c.name}</h3><ul>${c.focus.map(f=>`<li>${f}</li>`).join('')}</ul><a href="${c.url}" target="_blank" rel="noreferrer">官方网站 ↗</a></article>`).join('')}</div></section>`}
function renderPlaceholder(title,desc){return `<div class="empty panel"><h2>${title}</h2><p>${desc}</p></div>`}
function calcLab(){const get=id=>document.getElementById(id);if(!get('itLoad'))return;const it=+get('itLoad').value,pue=+get('pue').value,rp=+get('rackPower').value,cdu=+get('cduPower').value,dt=+get('deltaT').value,red=+get('redundancy').value;const facility=it*pue,racks=Math.ceil((it*1000)/rp),cdus=Math.ceil((it/cdu)*red),annual=facility*8760/1000;get('itLoadV').textContent=`${it} MW`;get('pueV').textContent=pue.toFixed(2);get('rackPowerV').textContent=`${rp} kW`;get('cduPowerV').textContent=`${cdu.toFixed(1)} MW`;get('deltaTV').textContent=`${dt} ℃`;get('facilityLoad').textContent=`${fmt(facility,1)} MW`;get('rackCount').textContent=fmt(racks);get('cduCount').textContent=fmt(cdus);get('annualEnergy').textContent=`${annual.toFixed(2)} TWh`;}
const faultText={"CDU 故障":["液冷回路能力下降","压差 / 流量异常 → GPU 入口温度抬升 → 热保护风险；应切换冗余 CDU 并限制受影响机柜负载。"],"UPS 故障":["供电路径进入降级状态","旁路或冗余链路接管；若故障域设计不合理，可能影响一组机柜甚至触发作业迁移。"],"交换机拥塞":["网络有效算力下降","ECN/PFC、队列和重传指标恶化；GPU 仍在耗电，但训练 step time 上升，形成“高功耗低产出”。"],"GPU Hotspot":["局部芯片温度异常","可能由冷板接触、流量分配或 TIM 问题造成；策略可包括降频、作业迁移和维护。"],"冷却流量不足":["换热能力不足","根据 Q=ṁcₚΔT，流量下降会要求更大的温差或造成热量无法及时带走。"]};
function bindPage(){document.querySelectorAll('[data-go]').forEach(b=>b.onclick=()=>{const [d,v]=b.dataset.go.split(',');nav(d,v)});document.querySelectorAll('[data-article]').forEach(b=>b.onclick=()=>{const id=b.dataset.article;const a=A.articles[id];if(a){app.innerHTML=`${subnav(a.domain,'knowledge')}${renderArticle(id)}`;bindPage();}});document.querySelectorAll('[data-knowledge]').forEach(n=>n.onclick=()=>{const id=n.dataset.knowledge;if(A.articles[id]){app.innerHTML=`${subnav(state.domain,'knowledge')}${renderArticle(id)}`;bindPage();}});['itLoad','pue','rackPower','cduPower','deltaT','redundancy'].forEach(id=>document.getElementById(id)?.addEventListener('input',calcLab));calcLab();document.querySelectorAll('[data-fault]').forEach(b=>b.onclick=()=>{document.querySelectorAll('[data-fault]').forEach(x=>x.classList.remove('active'));b.classList.add('active');const [t,p]=faultText[b.dataset.fault];document.getElementById('faultPanel').innerHTML=`<b>${t}</b><p class="tiny">${p}</p>`;});}
function searchAll(q){q=q.trim().toLowerCase();if(!q)return[];const out=[];Object.entries(A.articles).forEach(([id,a])=>{const txt=[a.title,a.lead,a.category,...a.sections.flat()].join(' ').toLowerCase();if(txt.includes(q))out.push({title:a.title,meta:`${domainName(a.domain)} · ${a.category}`,action:()=>{const u=new URL(location.href);u.searchParams.set('domain',a.domain);u.searchParams.set('view','knowledge');history.pushState({},'',u);state.domain=a.domain;state.view='knowledge';app.innerHTML=`${subnav(a.domain,'knowledge')}${renderArticle(id)}`;bindPage();document.getElementById('searchDialog').close();}})});allNews().forEach(n=>{const txt=[n.title,n.company,n.technology,n.what_changed].join(' ').toLowerCase();if(txt.includes(q))out.push({title:n.title,meta:`${domainName(n.domain)} · ${n.category}`,url:n.url})});return out.slice(0,15)}
document.querySelectorAll('.domain-nav button').forEach(b=>b.onclick=()=>nav(b.dataset.domain,b.dataset.domain==='home'?'today':'overview'));
document.getElementById('themeBtn').onclick=()=>{document.body.classList.toggle('light');localStorage.setItem('atlasTheme',document.body.classList.contains('light')?'light':'dark')};if(localStorage.getItem('atlasTheme')==='light')document.body.classList.add('light');
const dlg=document.getElementById('searchDialog'),input=document.getElementById('globalSearch'),results=document.getElementById('searchResults');document.getElementById('searchBtn').onclick=()=>{dlg.showModal();setTimeout(()=>input.focus(),60)};input.oninput=()=>{const r=searchAll(input.value);results.innerHTML=r.map((x,i)=>`<a href="${x.url||'#'}" ${x.url?'target="_blank" rel="noreferrer"':''} class="search-hit" data-hit="${i}">${esc(x.title)}<small>${esc(x.meta)}</small></a>`).join('');results.querySelectorAll('[data-hit]').forEach(el=>{const x=r[+el.dataset.hit];if(x.action)el.onclick=e=>{e.preventDefault();x.action()}})};
window.addEventListener('popstate',render);
fetch('./data/daily.json', {cache:'no-store'}).then(r=>r.ok?r.json():null).then(d=>{ if(d?.items?.length){ A.dynamicNews=d.items; render(); }}).catch(()=>{});
render();
