'use client';
import {useState} from 'react';
import {Input} from '@/components/ui/input';
import {CaseChart} from '@/components/case-chart';
import {LearningDiagram} from '@/components/learning-diagram';
const links=(ids:string[],names:string[])=><div className="step-links">{ids.map((id,i)=><a key={id} href={'/read/'+id}>{names[i]}</a>)}</div>;
export default function CaseStudy(){
 const [load,setLoad]=useState('70'),[pue,setPue]=useState('1.25'),[price,setPrice]=useState('0.7'),[fraction,setFraction]=useState('80'),[delta,setDelta]=useState('10'),[ua,setUa]=useState('40');
 const l=+load,p=+pue,c=+price,f=+fraction,d=+delta,u=+ua;
 const valid=[load,pue,price,fraction,delta,ua].every(x=>x.trim()!==''&&Number.isFinite(+x))&&l>0&&l<=100&&p>=1&&p<=3&&c>=0&&f>0&&f<=100&&d>=1&&d<=30&&u>0&&u<=150;
 const it=1000*l/100,facility=it*p,heat=it*f/100,flow=heat/(4.18*d)*60,annual=facility*8760*c/10000;
 // Single lumped thermal node, independent teaching transient, explicit kJ/kW/s units.
 const C=12000,Ts=20,T0=30;const temps=Array.from({length:13},(_,i)=>{const t=i*60;const temp=(k:number)=>Ts+heat/k+(T0-Ts-heat/k)*Math.exp(-k*t/C);return {minute:i,normal:+temp(u).toFixed(2),degraded:+temp(u*.6).toFixed(2)};});
 const costs=[1.1,1.2,1.3,1.4,1.5].map(x=>({pue:x,cost:+(it*x*8760*c/10000).toFixed(2)}));
 return <><header className="read-header"><a className="brand" href="/"><span className="brand-mark">A</span><b>知域<span> ATLAS</span></b></a><a href="/?view=cases">返回案例研习</a></header><main className="shell"><section className="case-hero"><span className="eyebrow">INTEGRATED CASE / AIDC × ROBOTICS × MACHINE LEARNING</span><h1>一座 1 MW 液冷机房，<br/>怎样形成机器人巡检闭环？</h1><p>从容量、供电和冷却建模，到机器人感知、世界模型推演、小模型预警与智能体工单。所有计算共用一组输入，逐步解释每个环节的作用。</p><span className="tag">教学建模 · 非真实客户项目 · 不连接控制设备</span></section>
 <section className="case-section"><h2>01 / 先定义业务与系统边界</h2><p>假设 20 个生产机柜，每柜额定 IT 功率 50 kW，总额定容量 1,000 kW。额定容量用于供电与空间规划，负载率用于本例能耗估算。这里的“负载率”专指平均 IT 实测功率占额定容量比例，不是 GPU 利用率。任务是自动巡检 80 个点位，发现异常后复核并生成工单，由值班人员决定处置。</p><div className="map-scroll"><svg className="system-map" viewBox="0 0 960 360" role="img" aria-label="机房电力、热流和机器人数据闭环系统图"><defs><marker id="arrow" markerWidth="8" markerHeight="8" refX="7" refY="3" orient="auto"><path d="M0,0 L0,6 L8,3 Z" fill="#628c88"/></marker></defs><g fill="#fff" stroke="#a7c4be" strokeWidth="1.5"><rect x="25" y="60" width="160" height="70" rx="7"/><rect x="245" y="60" width="200" height="70" rx="7"/><rect x="505" y="60" width="175" height="70" rx="7"/><rect x="750" y="60" width="185" height="70" rx="7"/><rect x="25" y="240" width="160" height="70" rx="7"/><rect x="245" y="240" width="200" height="70" rx="7"/><rect x="505" y="240" width="175" height="70" rx="7"/><rect x="750" y="240" width="185" height="70" rx="7"/></g><g fill="#183e4a" textAnchor="middle" fontSize="17"><text x="105" y="88">供电链路</text><text x="105" y="112" fontSize="13">市电 · UPS · PDU</text><text x="345" y="88">20 × 50 kW 机柜</text><text x="345" y="112" fontSize="13">GPU / 网络 / 存储</text><text x="593" y="88">冷板 / CDU</text><text x="593" y="112" fontSize="13">机侧与设施侧换热</text><text x="843" y="88">设施冷源</text><text x="843" y="112" fontSize="13">冷却塔或其他散热设施</text><text x="105" y="269">机器人巡检</text><text x="105" y="293" fontSize="13">视觉 / 热像 / 定位</text><text x="345" y="269">数据与小模型</text><text x="345" y="293" fontSize="13">时序预测 / 异常置信度</text><text x="593" y="269">世界模型</text><text x="593" y="293" fontSize="13">候选路线 / 风险推演</text><text x="843" y="269">智能体与工单</text><text x="843" y="293" fontSize="13">证据汇总 / 人工批准</text></g><g fill="none" stroke="#628c88" strokeWidth="2" markerEnd="url(#arrow)"><path d="M185 95 H245"/><path d="M445 95 H505"/><path d="M680 95 H750"/><path d="M185 275 H245"/><path d="M445 275 H505"/><path d="M680 275 H750"/><path d="M345 130 V240"/><path d="M505 290 H475 V337 H105 V310"/></g><g fill="#69837e" fontSize="12" textAnchor="middle"><text x="215" y="83">电力</text><text x="475" y="83">热量</text><text x="715" y="83">热量</text><text x="398" y="187">设备遥测</text><text x="282" y="354">可行路线反馈；安全控制器独立约束动作</text></g></svg></div><p className="muted">图中上层表示能量流向，真实冷却液另有供回双管；下层表示信息与决策。工单系统没有直接控制供电与冷却设备的通路。</p></section>
 <section className="case-section" id="infrastructure"><h2>02 / 调整工况，观察影响</h2><div className="case-inputs">{[{name:'平均 IT 负载率 / %',v:load,s:setLoad,min:1,max:100,step:1},{name:'全年平均 PUE',v:pue,s:setPue,min:1,max:3,step:.01},{name:'电价 / 元·kWh⁻¹',v:price,s:setPrice,min:0,max:10,step:.01},{name:'液冷热量比例 / %',v:fraction,s:setFraction,min:1,max:100,step:1},{name:'冷却液温升 / K',v:delta,s:setDelta,min:1,max:30,step:1},{name:'等效 UA / kW·K⁻¹',v:ua,s:setUa,min:1,max:150,step:1}].map(x=><label key={x.name}>{x.name}<Input type="number" value={x.v} min={x.min} max={x.max} step={x.step} onChange={e=>x.s(e.target.value)}/></label>)}</div>{!valid?<p role="alert">请输入有效参数：负载率与液冷比例 1–100%，PUE 1–3，温升 1–30 K，UA 0–150（大于 0），电价不小于 0。</p>:<><div className="case-output" aria-live="polite"><div><span>平均 IT 功率</span><strong>{it.toFixed(0)} kW</strong><small>额定 1,000 kW × 负载率</small></div><div><span>设施总平均功率</span><strong>{facility.toFixed(1)} kW</strong><small>IT 功率 × PUE</small></div><div><span>年度电费</span><strong>{annual.toFixed(2)} 万元</strong><small>按 8,760 h 恒定工况</small></div><div><span>液冷总质量流量近似体积流量</span><strong>{flow.toFixed(1)} L/min</strong><small>以水密度 1 kg/L 近似</small></div></div><div className="case-grid"><div><h3>电力与能耗：不要混用额定和平均值</h3><div className="formula-box">P̄_IT = 20 × 50 × L<br/>P̄_total = P̄_IT × PUE<br/>Cost = P̄_total × 8,760 × c</div><p>L 为平均功率负载率的小数，c 为电价。供电冗余与容量应根据峰值及故障工况设计，不应按这里的平均 {it.toFixed(0)} kW 直接缩小。当前设施辅助功率近似为 {(facility-it).toFixed(1)} kW，包含冷却、供配电损耗等，不等同冷机功率。</p>{links(['a01','a02','a03','a11'],['土建规划','供配电','冗余','PUE 与成本'])}</div><div><h3>液冷：由热负荷反推流量</h3><div className="formula-box">Q_liquid = P̄_IT × f<br/>ṁ = Q_liquid / (cₚ ΔT)<br/>V̇ ≈ 60ṁ / ρ</div><p>f 为液冷热量比例，cₚ=4.18 kJ/(kg·K)，ΔT 为供回液温差，ρ≈1 kg/L。当前液冷承担 {heat.toFixed(1)} kW，残余风冷承担 {(it-heat).toFixed(1)} kW；每柜约 {(flow/20).toFixed(1)} L/min。这里只算稳态热平衡，压降、泵曲线、水质与露点需另行校核。</p>{links(['a04','a05','a14'],['双回路液冷','气流组织','流量核算'])}</div></div><div className="chart-card"><h3>PUE 对电费的影响</h3><p>教学敏感性分析 · 固定当前 IT 平均功率与电价 · 纵轴 万元/年</p><div className="chart-holder"><CaseChart data={costs} xKey="pue" xLabel="PUE" yLabel="万元 / 年" series={[{key:"cost",name:"年度电费",color:"#168574"}]}/></div><p>PUE 从 1.3 降至 1.2，按当前条件理论节省 {(it*.1*8760*c/10000).toFixed(2)} 万元/年。尚未扣除改造成本、维护增量和融资成本，不能直接认定投资收益。</p></div></>}</section>
 <section className="case-section"><h2>03 / 用热动态模型解释“为什么要提前发现”</h2><div className="formula-box">C · dT/dt = Q − UA(T − Tₛ)<br/>T(t) = Tₛ + Q/UA + [T₀ − Tₛ − Q/UA] e⁻ᵁᴬᵗ/ᶜ</div><p>这是单个等效热节点的教学模型：C=12,000 kJ/K 为假设热容，T 为等效温度，T₀=30°C，Tₛ=20°C 为固定冷源温度，Q 使用本例液冷热负荷，UA 为等效换热能力，t 以秒计。假设热源恒定、混合均匀且无控制动作，图中“衰减”表示 UA 下降 40%。它不是实际芯片结温、机柜入口温度或设备安全阈值。</p>{valid&&<div className="chart-card"><h3>换热能力衰减后的温度响应</h3><p>纵轴 等效温度 / °C · 横轴 时间 / min · 全部为模型计算</p><div className="chart-holder"><CaseChart data={temps} xKey="minute" xLabel="时间 / min" yLabel="等效温度 / °C" series={[{key:"normal",name:"基准 UA",color:"#168574"},{key:"degraded",name:"UA 衰减 40%",color:"#c87c32",dashed:true}]}/></div><details><summary>查看模型输出数值</summary><table className="data-table"><thead><tr><th>min</th><th>基准 / °C</th><th>衰减 / °C</th></tr></thead><tbody>{temps.map(t=><tr key={t.minute}><td>{t.minute}</td><td>{t.normal}</td><td>{t.degraded}</td></tr>)}</tbody></table></details></div>}<p>真实项目先通过带载试验辨识 C 与 UA，使用多个测点检验温度滞后。若模型和实测持续偏离，应检查传感器、流量、阀位和负载变化，不能直接认定换热器故障。小模型可预测 Q 或残差，物理方程用于约束方向与能量闭合。</p>{links(['a10','m07','m09'],['遥测体系','时序预测','可靠度与降级'])}</section>
 <section className="case-section" id="robot"><h2>04 / 机器人如何把“异常”变成可靠证据</h2><LearningDiagram nodes={['定位到点位','图像/热像采集','质量检查','遥测交叉核对','工单证据包']} title="巡检任务链"/><div className="case-grid"><div><h3>本体与感知</h3><p>移动底盘完成点位到达，云台相机采集表计、标签和外观，热像仪记录可见表面热分布。先校验拍摄姿态、遮挡、反光和温度发射率设置，再判定读数有效。必要时改换视角重采。机械臂只在另行验证的接触任务中加入，不是完成巡检的必需条件。</p>{links(['r02','r03','r04','r05'],['关节硬件','传感融合','机械臂','灵巧手'])}</div><div><h3>导航与低层保护</h3><p>导航规划绕开通道障碍并避让人员。以速度0.5m/s、反应0.2s、减速度0.5m/s²示例，理想停止距离0.35m，再加定位与测量裕量。定位丢失、路径不可通行或急停触发时停止任务，世界模型和大模型都不能覆盖这一规则。</p>{links(['r01','r06','r10','r11'],['系统分层','控制','ROS 2','移动导航'])}</div></div></section>
 <section className="case-section" id="intelligence"><h2>05 / 三种智能能力，各自解决什么问题？</h2><div className="table-wrap"><table className="data-table"><thead><tr><th>模块</th><th>输入 / 输出</th><th>模型与验收</th><th>失败后的行为</th></tr></thead><tbody><tr><td>小模型 · 预测预警</td><td>最近 30 min 功率、温度、流量 → 未来 5 min 趋势与区间</td><td>持续值基线与 TCN / 树模型对比；按时间切分，测 MAE 和区间覆盖</td><td>缺测、漂移或超范围时退回规则与人工复核</td></tr><tr><td>世界模型 · 复核规划</td><td>位姿、障碍、观察目标 → 候选路线的风险与可见性</td><td>比较不同动作的未来状态；只执行首段；真实闭环验证增益</td><td>不确定性升高则缩短规划、重观测或停止</td></tr><tr><td>大模型 / RAG</td><td>异常证据与规程 → 有引用的原因假设与检查建议</td><td>引用准确、版本正确、原因假设有证据；无法确认则保留未知</td><td>不编造设定值，不以语言推断替代测量</td></tr><tr><td>智能体 · 工作流</td><td>遥测查询、文档检索、复核结果 → 工单草稿</td><td>核验设备 ID、时段、权限、幂等键与结果，留存工具轨迹</td><td>写入失败不报成功；设备操作需独立授权</td></tr></tbody></table></div><p>例如，同一机柜连续出现温度上升、流量下降，模型先提出“冷却能力异常”假设。机器人复核显示无泄漏，但阀位状态与预期不一致；智能体汇总趋势、照片、时间戳、规程引用和候选原因，生成待审核工单。以上是教学情景，不是已经发生的事故记录。</p>{links(['w01','w02','w03','m02','m04','m05','m06'],['世界模型原理','MPC 推演','世界模型评测','RAG','智能体架构','上下文工程','智能体验收'])}</section>
 <section className="case-section"><h2>06 / 计算资源、网络与证据存储怎样配合</h2><p>边缘计算设备承担导航、实时预处理和小模型推理，集中 GPU 服务承担较重的视觉语言理解与模型训练。训练网络、机器人控制网络和管理网络应有明确的隔离及服务质量边界。证据对象存储按事件保存原图与时序片段，数据库保存点位、设备、版本和引用关系；日志不能只留下大模型最终答案。</p><p>延迟预算示例：采集100ms、预处理40ms、边缘识别80ms、网络50ms，总计270ms，可用于低频巡检判断，不能替代毫秒级伺服回路。联网推理不可用时，机器人保留安全停车与返航策略；是否返航取决于定位与路径是否可靠。</p>{links(['a06','a07','a08','a09','m03','m08'],['服务器瓶颈','网络通信','存储与恢复','集群调度','推理服务','量化部署'])}</section>
 <section className="case-section"><h2>07 / 如何验收这一套系统</h2><table className="data-table"><thead><tr><th>层级</th><th>记录与测试</th><th>解释边界</th></tr></thead><tbody><tr><td>设施</td><td>核对电量边界，测供回温差与流量，验证失流与报警</td><td>教学模型不能替代联合调试与保护测试</td></tr><tr><td>巡检</td><td>80点位到达78、有效读数72，有效覆盖率90%</td><td>到达率97.5%不等于巡检完成率</td></tr><tr><td>模型</td><td>跨日期、负载和异常类型评测；检查预测区间覆盖</td><td>不能将相邻时间窗随机混入训练和测试</td></tr><tr><td>闭环</td><td>100任务成功90次，Wilson95%区间约82.6%–94.5%</td><td>依赖独立试验假设，不代表罕见风险已获认证</td></tr><tr><td>运营</td><td>每千任务接管数、误报/漏报、平均恢复时间、工单闭环</td><td>示例不推算人员节省；收益需来自真实运营数据</td></tr></tbody></table><p>先在影子模式下只记录建议，再开放工单草稿，最后依据验证结果决定授权范围。模型、阈值、规程、设备映射和软件版本一起冻结，变更后进行回归与回滚演练。</p>{links(['a12','r12','r14','m06'],['综合验收','机器人评测','巡检验收','智能体门禁'])}</section>
 <section className="case-section"><h2>资料与复算依据</h2><p>热平衡与一阶动态模型为本站原创教学推导；初始值、UA、热容、成功次数均为假设。技术延伸：<a href="https://www.opencompute.org/" target="_blank" rel="noreferrer">OCP</a>、<a href="https://docs.ros.org/en/jazzy/" target="_blank" rel="noreferrer">ROS 2</a>、<a href="https://github.com/facebookresearch/vjepa2" target="_blank" rel="noreferrer">V-JEPA</a>。各章节链接提供更完整手册与来源。</p></section></main><footer className="footer">知域 ATLAS · 综合案例 · 2026-10-01</footer></>;
}
