'use client';
import {useState,useEffect,useMemo,useCallback,useRef,lazy,Suspense} from 'react';
import {useUpdates} from '@/hooks/use-updates';
import type {Indicators} from '@/lib/indicators';
const ResearchCenter=lazy(()=>import('@/components/research-center').then(m=>({default:m.ResearchCenter})));
const MarketChart=lazy(()=>import('@/components/market-chart').then(m=>({default:m.MarketChart})));
const WikiLibrary=lazy(()=>import('@/components/wiki-library').then(m=>({default:m.WikiLibrary})));
import {ArrowUpRight,ArrowRight,Search,RefreshCw,BookOpen,Layers3,Cpu,Network,Zap,Snowflake,Bot,GraduationCap,Globe2,CheckCircle2,AlertCircle,Clock3,Building2,FlaskConical,ChevronRight,SlidersHorizontal,Radio,Telescope,ExternalLink,Activity,Menu,Newspaper,FileText} from 'lucide-react';
import {Tabs,TabsList,TabsTrigger} from '@/components/ui/tabs';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {Input} from '@/components/ui/input';
import {Table,TableHeader,TableHead,TableBody,TableRow,TableCell} from '@/components/ui/table';
import {Skeleton} from '@/components/ui/skeleton';
import {articles,curated,companies,sources,newsTypes,type Domain,type News,type Article} from '@/lib/content';
import {concepts} from '@/lib/concepts';
import {WorldResearch} from '@/components/world-research';
type View='overview'|'library'|'news'|'companies'|'cases'|'research';
type Result={items:News[];statuses:{name:string;ok:boolean;count:number;error?:string;checkedAt:string;latestPublishedAt?:string;durationMs?:number}[];checkedAt:string;cached?:boolean};
const views:{key:View;title:string}[]=[{key:'overview',title:'领域总览'},{key:'library',title:'知识手册'},{key:'news',title:'产业动态'},{key:'companies',title:'企业观察'},{key:'cases',title:'案例研习'},{key:'research',title:'研报中心'}];
const icons=[Layers3,Zap,Snowflake,Cpu,Network,Activity,BookOpen,Bot];
function date(s:string){return s?new Date(s).toLocaleDateString('zh-CN',{year:'numeric',month:'2-digit',day:'2-digit'}):'日期未提供';}
export default function Portal(){
 const [mobileMenu,setMobileMenu]=useState(false);
 const [filtersOpen,setFiltersOpen]=useState(true);
 useEffect(()=>{const media=window.matchMedia('(max-width: 600px)');const sync=()=>setFiltersOpen(!media.matches);sync();media.addEventListener('change',sync);return()=>media.removeEventListener('change',sync);},[]);
 const [region,setRegion]=useState('all');const [newsLimit,setNewsLimit]=useState(24);const [group,setGroup]=useState('全部');const [age,setAge]=useState('30');const [topic,setTopic]=useState('all');const [companyTab,setCompanyTab]=useState('企业概览');
 const [domain,setDomain]=useState<Domain>('aidc');const [view,setView]=useState<View>('overview');const [query,setQuery]=useState('');const [category,setCategory]=useState('全部');const [level,setLevel]=useState('全部');const [newsType,setNewsType]=useState('全部');
 const {data,loading,progress,added,error,isOld,refresh}=useUpdates(domain);
 const [sourceOpen,setSourceOpen]=useState(false),[company,setCompany]=useState<(typeof companies)[number]|null>(null),[today,setToday]=useState('');
 const [indicators,setIndicators]=useState<Indicators|null>(null),[metricLoading,setMetricLoading]=useState(false),[exporting,setExporting]=useState(false),[exportError,setExportError]=useState('');
 const [exportFile,setExportFile]=useState<{url:string;filename:string}|null>(null);
 useEffect(()=>()=>{if(exportFile)URL.revokeObjectURL(exportFile.url);},[exportFile]);
 useEffect(()=>{setExportFile(null);},[domain,region,age]);
 const metricRequest=useRef<Promise<Indicators|null>|null>(null);
 const loadMetrics=useCallback((force=false):Promise<Indicators|null>=>{
  if(metricRequest.current)return metricRequest.current;setMetricLoading(true);
  metricRequest.current=fetch('/api/indicators'+(force?'?force=1':''),{signal:AbortSignal.timeout(14000)}).then(r=>{if(!r.ok)throw Error();return r.json() as Promise<Indicators>;}).then(d=>{setIndicators(d);return d;}).catch(()=>{const d:Indicators={checkedAt:new Date().toISOString(),indicators:[],models:[],statuses:[{name:'数据服务',ok:false,error:'请求失败，请重试'}]};setIndicators(d);return d;}).finally(()=>{setMetricLoading(false);metricRequest.current=null;});return metricRequest.current!;
 },[]);
 useEffect(()=>{if(view!=='research')return;const check=()=>{if(document.visibilityState==='visible'&&(!indicators||Date.now()-Date.parse(indicators.checkedAt)>3600000))void loadMetrics();};check();const timer=setInterval(check,60000);return()=>clearInterval(timer);},[view,indicators,loadMetrics]);
 useEffect(()=>{const sync=()=>{const p=new URLSearchParams(location.search);setDomain(['aidc','robot','ml'].includes(p.get('domain')||'')?p.get('domain') as Domain:'aidc');const v=p.get('view');setView(views.some(x=>x.key===v)?v as View:window.matchMedia('(max-width: 600px)').matches?'news':'overview');setTopic(p.get('topic')==='world'?'world':'all');};sync();setToday(new Date().toLocaleDateString('zh-CN',{year:'numeric',month:'long',day:'numeric',weekday:'long',timeZone:'Asia/Shanghai'}));window.addEventListener('popstate',sync);return()=>window.removeEventListener('popstate',sync);},[]);

 function navigate(v:View,d:Domain=domain){setMobileMenu(false);window.scrollTo({top:0,behavior:'instant'});setView(v);setDomain(d);setQuery('');setCategory('全部');setLevel('全部');setNewsType('全部');setGroup('全部');setTopic('all');setCompanyTab('企业概览');setNewsLimit(24);setAge('30');history.pushState(null,'','/?domain='+d+'&view='+v);}
 const scoped=articles.filter(a=>a.domain===domain);const categories=[...new Set(scoped.filter(a=>a.kind==='手册'&&(group==='全部'||a.category.startsWith(group))).map(a=>a.category))];
 const mergedNews=useMemo(()=>{const live=data?.items||[];const urls=new Set(live.map(x=>x.url));return [...live,...(age==='archive'?curated.filter(x=>!urls.has(x.url)):[])].filter(x=>x.domain===domain&&(age==='archive'||Date.parse(x.date)>=Date.now()-Number(age)*86400000)&&(topic!=='world'||x.topics?.includes('world')||/world.model|世界模型|cosmos|v-jepa|genie/i.test(x.title))).sort((a,b)=>Date.parse(b.date)-Date.parse(a.date));},[data,domain,age,topic]);
 const q=query.trim().toLowerCase();const articleHits=scoped.filter(a=>(group==='全部'||a.category.startsWith(group))&&(!q||JSON.stringify([a,concepts.filter(c=>c.article===a.id)]).toLowerCase().includes(q))&&(category==='全部'||a.category===category)&&(level==='全部'||a.level===level));const companyHits=companies.filter(c=>c.domain===domain&&(!q||JSON.stringify(c).toLowerCase().includes(q)));const newsHits=mergedNews.filter(n=>(region==='all'||n.region==='cn')&&(!q||(n.title+n.source+n.summary).toLowerCase().includes(q))&&(newsType==='全部'||n.type===newsType));
 const reportItems=useMemo(()=>mergedNews.filter(n=>region==='all'||n.region==='cn'),[mergedNews,region]);
 async function exportCurrent(){if(exporting)return;setExporting(true);setExportError('');try{const [{downloadReport},metrics]=await Promise.all([import('@/lib/report'),indicators?Promise.resolve(indicators):loadMetrics()]);setExportFile(downloadReport({domain,items:reportItems,updates:data,indicators:metrics,region,age,loading}));}catch{setExportError('研报导出失败，请重试。');}finally{setExporting(false);}}
 const isA=domain==='aidc',isML=domain==='ml';const domainName=isA?'AIDC 智算中心':isML?'机器学习':'机器人与具身智能';const feature=scoped.find(a=>a.id===(isA?'a04':isML?'m01':'w01'))!;const successful=data?.statuses.filter(s=>s.ok).length||0;
 const activeFilters=[region==='cn'?'中国区':'全球',age==='archive'?'资料库':'近 '+age+' 天',...(topic==='world'?['世界模型']:[])].join(' · ');
 const newsRow=(n:News,i:number)=><a className="news-row" href={n.url} key={n.url+i} target="_blank" rel="noreferrer"><div className="news-meta"><span className={n.historical?'tag neutral':'tag'}>{n.historical?'资料库':n.type}</span><time dateTime={n.date}>{new Date(n.date).toLocaleString('zh-CN',{timeZone:'Asia/Shanghai',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',hour12:false})} 北京时间</time></div><h3>{n.title}<ArrowUpRight size={15}/></h3>{n.summary&&<p>{n.summary}</p>}<small>{n.source}{n.region==='cn'?' · 中国相关':''}{n.sourceKind?' · '+n.sourceKind:''}{n.historical?' · 历史资料':n.stale?' · 旧缓存 · 采集于 '+date(n.collectedAt||''):''}</small></a>;
 const articleCard=(a:Article,i:number)=>{const Icon=icons[i%icons.length];return <a href={'/read/'+a.id} className="knowledge-card" key={a.id}><div className="card-top"><span className="knowledge-icon"><Icon size={21}/></span><span>{a.level}</span></div><span className="card-category">{a.category}</span><h3>{a.title}</h3><p>{a.summary}</p><div className="card-bottom"><span><BookOpen size={14}/> {a.minutes} 分钟阅读</span><ArrowUpRight size={18}/></div></a>;};
 return <><div className="topline"><div><span>ALU / 专业知识与产业情报</span><span>{today||'AIDC × ROBOTICS'}<span className="timezone">北京时间</span></span></div></div>
 <header className="site-header"><a className="brand" href="/"><span className="brand-mark">A</span><b>知域<span> ATLAS</span></b></a><div className="header-caption">从算力基础设施<br/>到机器人与机器学习</div><div className="searchbox"><Search size={19}/><Input value={query} onChange={e=>setQuery(e.target.value)} placeholder={'搜索'+domainName+'知识、技术、企业…'} aria-label="搜索当前领域全部内容"/>{query&&<button onClick={()=>setQuery('')} aria-label="清空搜索">×</button>}</div><button className="source-button" onClick={()=>setSourceOpen(true)}><Globe2 size={18}/><span>信息源</span></button></header>
 <div className="nav-wrap"><div className="nav-inner"><Tabs value={domain} onValueChange={d=>navigate(view,d as Domain)}><TabsList className="domain-tabs"><TabsTrigger value="aidc"><Cpu size={18}/> AIDC 智算中心</TabsTrigger><TabsTrigger value="robot"><Bot size={18}/> 机器人与具身智能</TabsTrigger><TabsTrigger value="ml"><Network size={18}/> 机器学习</TabsTrigger></TabsList></Tabs><nav aria-label="主导航">{views.map(v=><button key={v.key} className={view===v.key?'active':''} onClick={()=>navigate(v.key)}>{v.title}</button>)}</nav></div></div>
 <main className={"shell portal-shell view-"+view}><div className="page-heading"><div><div className="eyebrow">{isA?'AI DATA CENTER':isML?'MACHINE LEARNING':'ROBOTICS & EMBODIED AI'} / KNOWLEDGE INTELLIGENCE</div><h1>{query?'搜索结果':view==='overview'?domainName:views.find(v=>v.key===view)?.title}<span className="heading-note">{view==='overview'?'知识有体系，洞察有依据。':domainName}</span></h1></div><div className="page-actions"><button className="refresh-button" onClick={exportCurrent} disabled={exporting}>{exporting?'正在生成研报…':'导出本领域研报'}</button><button className={'refresh-button '+(loading?'busy':'')} onClick={()=>void refresh(true)} disabled={loading}><RefreshCw size={15}/>{loading?'正在联网更新':'刷新资讯'}</button></div></div>{exportError&&<p role="alert">{exportError}</p>}{exportFile&&<p role="status" className="export-ready">研报文件已生成。如未自动下载，<a href={exportFile.url} download={exportFile.filename}>点击保存 {exportFile.filename}</a>。打开文件后可打印或保存 PDF。</p>}
 <div className={'update-line '+(error?'warning':'')}><span><span className={'status-dot '+(!successful||isOld?'offline':'')}/>{loading?'正在逐源更新 '+progress+'/'+sources.length+' · 成功结果已即时显示':error||('已连接 '+successful+'/'+sources.length+' 个来源 · '+(isOld?'显示本机缓存':'本次新增 '+added+' 条 · '+(successful<sources.length?'部分来源失败':'全部来源已检查')))}</span><button onClick={()=>setSourceOpen(true)}>{data?'采集于 '+new Date(data.checkedAt).toLocaleString('zh-CN',{timeZone:'Asia/Shanghai',hour12:false}):'查看来源与更新机制'}<ChevronRight size={13}/></button></div>
 {q?<section className="search-results"><div className="section-heading"><h2>“{query}”</h2><span>{articleHits.length+companyHits.length+newsHits.length} 项结果 · 当前领域</span></div><h3 className="results-label">知识与案例 · {articleHits.length}</h3><div className="knowledge-grid">{articleHits.map(articleCard)}</div><h3 className="results-label">企业 · {companyHits.length}</h3><div className="company-mini-grid">{companyHits.map(c=><button key={c.name} className="company-mini" onClick={()=>setCompany(c)}><b>{c.name}</b><span>{c.area}</span><ArrowUpRight size={17}/></button>)}</div><h3 className="results-label">产业动态 · {newsHits.length}</h3><div className="news-list">{newsHits.slice(0,newsLimit).map(newsRow)}{newsHits.length>newsLimit&&<button className="all-news" onClick={()=>setNewsLimit(n=>n+24)}>加载更多搜索结果</button>}</div>{!articleHits.length&&!companyHits.length&&!newsHits.length&&<div className="empty"><Search/><h3>暂未找到相关内容</h3><p>试试“液冷”“世界模型”“RAG”或切换另一领域。</p></div>}</section>
 :view==='research'?<Suspense fallback={<p className="empty">正在载入研报中心…</p>}><div className="time-filter"><span>研报范围</span>{[['all','全球'],['cn','中国区']].map(([k,v])=><button key={k} className={region===k?'selected':''} onClick={()=>setRegion(k)}>{v}</button>)}{[['7','近 7 天'],['30','近 30 天'],['90','近 90 天']].map(([k,v])=><button key={k} className={age===k?'selected':''} onClick={()=>setAge(k)}>{v}</button>)}</div><ResearchCenter domain={domain} items={reportItems} updates={data} indicators={indicators} metricLoading={metricLoading} onMetrics={()=>void loadMetrics(true)} onExport={exportCurrent} exporting={exporting}/></Suspense>:view==='overview'?<>
 <section className="metric-strip" aria-label="领域资料快览">
 <div><span>知识手册</span><strong>{scoped.filter(a=>a.kind==='手册').length}<small> 个专题</small></strong><p>从基础概念到工程实践</p></div><div><span>企业观察</span><strong>{companies.filter(c=>c.domain===domain).length}<small> 家企业</small></strong><p>技术路线 / 财报原文</p></div>
 <div><span>{isA?'全球数据中心用电预测':isML?'学习体系':'机器人软件工作流'}</span><strong>{isA?'950':isML?'3 大方向':'感知 → 动作'}<small>{isA?' TWh':''}</small></strong><p>{isA?'2030 预测 · IEA 2026':isML?'大模型 · 智能体 · 小模型':'数据采集 · 训练 · 部署 · 评测'}</p></div><div><span>{isA?'NVIDIA 数据中心营收':isML?'完整学习路径':'世界模型专题'}</span><strong>{isA?'890':isML?'训练 → 应用':'预测 → 规划'}<small>{isA?' 亿美元':''}</small></strong><p>{isA?'FY2027 Q2 · 非实时行情':isML?'数据 · 评测 · 部署 · 成本':'原理 · 训练 · 评测 · 研究路线'}</p></div></section>
 <div className="editorial-grid"><section className="featured-area"><div className="section-heading"><h2><span className="section-bar"/>本期深读</h2><span className="muted">连接原理与实践</span></div><a href={'/read/'+feature.id} className={'feature '+(!isA?'robot-feature':'')}><div className="feature-visual" aria-hidden="true"/><div className="feature-content"><span className="feature-label">{isA?'基础设施 / 制冷系统':isML?'机器学习 / 模型原理':'机器人 / 世界模型'}</span><h2>{isA?<>算力密度跃升，<br/>读懂液冷的完整链路。</>:isML?<>从预测下一个词，<br/>到可靠完成一项任务。</>:<>理解环境怎样变化，<br/>再决定下一步动作。</>}</h2><p>{feature.summary}</p><span className="feature-link">阅读专题 <ArrowUpRight size={18}/></span></div><span className="feature-index">{isA?'01 / INFRASTRUCTURE':isML?'03 / MACHINE LEARNING':'02 / EMBODIED INTELLIGENCE'}</span></a><div className="feature-subcards">{(isA?['a07','a11']:isML?['m04','m07']:['r05','w02']).map((id,i)=>{const a=articles.find(x=>x.id===id)!;return <a key={id} href={'/read/'+id}><span className="sub-index">0{i+2}</span><div><span className="card-category">{a.category}</span><h3>{a.title}</h3><p>{a.summary}</p></div><ArrowUpRight size={18}/></a>;})}</div></section>
 <aside className="updates-panel"><div className="section-heading"><h2><Radio size={19}/>产业快讯</h2><button onClick={()=>navigate('news')}>全部 <ArrowRight size={15}/></button></div><div className="feed-note">{data&&!isOld?'联网订阅 · 按原始发布日期排序':'最近 30 天 · 等待联网更新'}</div>{loading&&!data?<div className="loading-feed">{[1,2,3].map(i=><div key={i}><Skeleton className="h-4 w-20 mb-3"/><Skeleton className="h-12 w-full"/></div>)}</div>:mergedNews.slice(0,4).map(newsRow)}{!loading&&!mergedNews.length&&<div className="empty"><p>当前时段尚无成功采集的动态；可查看来源状态或切换资料库。</p></div>}<button className="all-news" onClick={()=>navigate('news')}>浏览全部产业动态<ArrowRight size={16}/></button></aside></div>
 <section className="knowledge-section"><div className="section-heading"><h2><span className="section-bar"/>专业知识导航</h2><button onClick={()=>navigate('library')}>完整知识手册 <ArrowRight size={16}/></button></div><div className="topic-rail">{categories.slice(0,8).map(c=><button key={c} onClick={()=>{navigate('library');setCategory(c);}}>{c}<ChevronRight size={13}/></button>)}</div><div className="knowledge-grid">{scoped.filter(a=>a.kind==='手册').slice(0,4).map(articleCard)}</div></section>
 <section className="bottom-split"><div><div className="section-heading"><h2>企业观察</h2><button onClick={()=>navigate('companies')}>查看全部 <ArrowRight size={15}/></button></div><div className="company-mini-grid">{companies.filter(c=>c.domain===domain).map(c=><button key={c.name} className="company-mini" onClick={()=>setCompany(c)}><span className="company-avatar" style={{color:c.color}}>{c.name.slice(0,2)}</span><div><b>{c.name}</b><span>{c.area}</span></div><ArrowUpRight size={15}/></button>)}</div></div><div className="practice-banner"><span className="eyebrow">FROM THEORY TO PRACTICE</span><h2>把三个领域，串联成一个完整系统。</h2><p>在液冷智算机房案例中理解能源、感知、预测、规划与智能体，调整参数观察系统响应。</p><button onClick={()=>navigate('cases')}>进入案例研习 <ArrowUpRight size={17}/></button></div></section>
 <Suspense fallback={<p>正在载入图表…</p>}><MarketChart domain={domain}/></Suspense>{domain==='robot'&&<WorldResearch/>}</>:view==='library'||view==='cases'?<section><div className="section-heading"><h2>{view==='cases'?'案例与工程推演':'知识百科 · 按词条查阅'}</h2><span className="muted">{view==='cases'?'示例与真实资料明确区分':'定义 / 工作原理 / 推导算例 / 参考资料'}</span></div>{view==='library'&&<><div className="group-tabs">{(domain==='robot'?['全部','软件','硬件']:domain==='ml'?['全部','大模型','智能体','小模型']:['全部']).map(g=><button key={g} className={group===g?'selected':''} onClick={()=>{setGroup(g);setCategory('全部');}}>{g==='全部'?'全部方向':g}</button>)}</div><div className="filter-row"><SlidersHorizontal size={17}/>{['全部',...categories].map(c=><button key={c} onClick={()=>setCategory(c)} className={category===c?'selected':''}>{c}</button>)}</div><Tabs value={level} onValueChange={setLevel}><TabsList className="level-tabs">{['全部','基础','进阶'].map(l=><TabsTrigger key={l} value={l}>{l==='全部'?'全部难度':l}</TabsTrigger>)}</TabsList></Tabs></>}{view==='cases'&&<a className="case-inline" href="/case-study"><span className="eyebrow">跨领域综合案例 · 7 个环节 · 可调参数与动态图表</span><h2>1 MW 液冷机房的机器人巡检闭环</h2><p>从容量与热平衡，到世界模型、小模型和智能体，串联全部三大领域。</p></a>}{view==='library'?<Suspense fallback={<p>正在载入知识目录…</p>}><WikiLibrary articles={articleHits.filter(a=>a.kind==='手册')}/></Suspense>:<div className="knowledge-grid full-library">{articleHits.filter(a=>a.kind==='案例').map(articleCard)}</div>}{view==='library'&&!articleHits.filter(a=>a.kind==='手册').length&&<div className="empty"><BookOpen/><h3>当前筛选暂无内容</h3><button onClick={()=>{setCategory('全部');setLevel('全部');}}>重置筛选</button></div>}{view==='cases'&&domain!=='ml'&&<Calculator domain={domain}/>}<div className="info-notice"><GraduationCap size={22}/><p>学习建议：先通读基础专题，再结合现场系统图、设备说明和真实数据复核。本站提供学习手册，不替代施工设计、安全认证或投资建议。</p></div></section>
 :view==='news'?<section><details className="news-filter-panel" open={filtersOpen} onToggle={e=>setFiltersOpen(e.currentTarget.open)}><summary><SlidersHorizontal size={17}/><span>{activeFilters}</span><b>筛选</b></summary><div className="time-filter"><span>区域</span>{[['all','全球'],['cn','中国区']].map(([k,v])=><button key={k} className={region===k?'selected':''} onClick={()=>{setRegion(k);setNewsLimit(24);}}>{v}</button>)}<span>原文发布时间</span>{[['7','近 7 天'],['30','近 30 天'],['90','近 90 天'],['archive','全部 / 资料库']].map(([k,v])=><button key={k} className={age===k?'selected':''} onClick={()=>{setAge(k);setNewsLimit(24);}}>{v}</button>)}{domain==='robot'&&<button className={topic==='world'?'selected':''} onClick={()=>setTopic(topic==='world'?'all':'world')}>世界模型专题{topic==='world'?' · 已筛选':''}</button>}</div></details><div className="news-page"><div><div className="filter-row">{newsTypes.map(t=><button key={t} onClick={()=>{setNewsType(t);setNewsLimit(24);}} className={newsType===t?'selected':''}>{t}</button>)}</div><div className="feed-freshness"><b>{domainName} · {newsType}</b><span>当前筛选 {newsHits.length} 条 · 最新原文 {newsHits[0]?new Date(newsHits[0].date).toLocaleString('zh-CN',{timeZone:'Asia/Shanghai',hour12:false}):'暂无'}</span><small>按原文发布时间排序；刷新获取新条目，不改变旧文章的发布日期。</small></div><div className="news-list">{newsHits.slice(0,newsLimit).map(newsRow)}</div>{newsHits.length>newsLimit&&<button className="all-news" onClick={()=>setNewsLimit(n=>n+24)}>加载更多（已展示 {newsLimit} / {newsHits.length}）</button>}{!newsHits.length&&<div className="empty"><Telescope/><h3>暂无匹配动态</h3><p>{loading?'正在获取来源，成功后会自动显示。':'此时间范围尚未采集到对应条目；可能是来源失败或订阅源没有发布。可扩大时间范围并查看来源状态。'}</p></div>}{newsType==='市场洞察'&&<Suspense fallback={<p>正在载入图表…</p>}><MarketChart domain={domain}/></Suspense>}</div><aside className="methodology"><Globe2 size={26}/><h3>每天打开，连接行业现场。</h3><p>优先检查当前领域；页面可见时每 15 分钟检查更新，15 分钟内返回使用本机缓存。同一来源服务端缓存最多一小时，跨日或手动刷新重新采集。后台更新不阻塞页面切换。</p><p>新增华为中文官方订阅、量子位原站订阅及国内专题聚合。中国区按文章中的国内机构、企业和市场关键词筛选，可能存在漏收；中文媒体的海外报道仍归全球视图。标题保留原文，不自动编造中文摘要。新闻索引不代表独立核验，研究预印本不代表已完成同行评审。</p><button onClick={()=>setSourceOpen(true)}>查看来源健康状态<ArrowUpRight size={16}/></button><hr/><h3>财务数字不会悄悄变“新”</h3><p>企业页数字是注明报告期的核验快照。新公告进入动态流，但不会未经核对自动覆盖财务指标。</p></aside></div></section>
 :<section><div className="group-tabs">{['企业概览','技术进展','财务披露'].map(t=><button key={t} className={companyTab===t?'selected':''} onClick={()=>setCompanyTab(t)}>{t}</button>)}</div>{companyTab!=='企业概览'&&<div className="news-list"><div className="section-heading"><h2>{companyTab} · 最新线索</h2><span>近 30 天 · 联网索引，按原文核查</span></div>{mergedNews.filter(n=>companyTab==='财务披露'?n.type==='企业财报':['技术研究','研究论文','产品发布'].includes(n.type)).slice(0,24).map(newsRow)}{!mergedNews.some(n=>companyTab==='财务披露'?n.type==='企业财报':['技术研究','研究论文','产品发布'].includes(n.type))&&<div className="empty"><p>暂无已采集的对应披露。可使用下方官方入口查看，不用旧快照冒充最新财报。</p></div>}</div>}<div className="section-heading"><h2>技术路线与财务观察</h2><span className="muted">核验快照 · 非实时股价</span></div><div className="info-notice compact"><AlertCircle size={20}/><p>财务数据按各自报告期展示，不能跨币种、跨期间或跨利润口径直接排名。未核验指标不填估值。</p></div><div className="table-wrap"><Table><TableHeader><TableRow><TableHead>企业 / 代码</TableHead><TableHead>业务位置</TableHead><TableHead>报告期</TableHead><TableHead>收入 / 增长</TableHead><TableHead>利润率口径</TableHead><TableHead>详情</TableHead></TableRow></TableHeader><TableBody>{companyHits.map(c=><TableRow key={c.name}><TableCell><b>{c.name}</b><small>{c.code}</small></TableCell><TableCell>{c.area}</TableCell><TableCell>{c.period}</TableCell><TableCell>{c.revenue}</TableCell><TableCell>{c.margin}<small>{c.name==='ABB'?'Operational EBITA':'毛利率（有披露时）'}</small></TableCell><TableCell><button className="text-button" onClick={()=>setCompany(c)}>查看<ArrowUpRight size={15}/></button></TableCell></TableRow>)}</TableBody></Table></div><div className="company-explain-grid">{companyHits.map(c=><article key={c.name}><div className="company-title"><span className="company-avatar" style={{color:c.color}}>{c.name.slice(0,2)}</span><h3>{c.name}</h3></div><p>{c.tech}</p><div className="financial-note">{c.note}</div><button className="text-button" onClick={()=>setCompany(c)}>资料与财务来源<ArrowUpRight size={16}/></button></article>)}</div></section>}
</main><nav className="mobile-bottom-nav" aria-label="手机快捷导航">{([{key:'news',title:'资讯',icon:Newspaper},{key:'library',title:'手册',icon:BookOpen},{key:'companies',title:'企业',icon:Building2},{key:'research',title:'研报',icon:FileText}] as const).map(({key,title,icon:Icon})=><button key={key} aria-current={view===key?'page':undefined} className={view===key?'active':''} onClick={()=>navigate(key)}><Icon size={21}/><span>{title}</span></button>)}<button className={mobileMenu||view==='overview'||view==='cases'?'active':''} aria-haspopup="dialog" onClick={()=>setMobileMenu(true)}><Menu size={21}/><span>更多</span></button></nav><Dialog open={mobileMenu} onOpenChange={setMobileMenu}><DialogContent className="atlas-dialog mobile-menu-dialog"><DialogHeader><DialogTitle>浏览知域</DialogTitle><DialogDescription>{domainName}</DialogDescription></DialogHeader><div className="mobile-menu-links">{views.map(v=><button key={v.key} onClick={()=>navigate(v.key)}>{v.title}<ChevronRight size={18}/></button>)}<button onClick={()=>{setMobileMenu(false);setSourceOpen(true);}}>信息来源与更新状态<Globe2 size={18}/></button></div></DialogContent></Dialog><footer className="footer portal-footer"><a className="brand footer-brand" href="/"><span className="brand-mark">A</span><b>知域<span> ATLAS</span></b></a><span>专业知识 · 可靠来源 · 持续探索</span><button onClick={()=>setSourceOpen(true)}>资料来源与更新说明<ArrowUpRight size={14}/></button><form method="post" action="/auth/logout"><button type="submit">退出登录</button></form><small>手册修订 2026-10-01 · 财务快照注明报告期 · 不构成工程或投资建议</small><small>配图：CERN（2009） / Florian Hirzinger · <a href="https://commons.wikimedia.org/wiki/File:CERN_Server_03.jpg" target="_blank" rel="noreferrer">原图</a> · <a href="https://creativecommons.org/licenses/by-sa/3.0/" target="_blank" rel="noreferrer">CC BY-SA 3.0</a> · 裁切与遮罩处理，仅作机房示意</small></footer>
 <Dialog open={sourceOpen} onOpenChange={setSourceOpen}><DialogContent className="atlas-dialog"><DialogHeader><DialogTitle>信息来源与更新状态</DialogTitle><DialogDescription>自动更新公开资讯；知识正文与财务快照保留各自核验日期。</DialogDescription></DialogHeader><div className="source-status">{sources.map(s=>{const st=data?.statuses.find(x=>x.name===s.name);return <div key={s.name}><div><b>{s.name}</b><span className={st?.ok?'ok':'muted'}>{st?(st.ok?(isOld?'上次成功':'已连接')+' · '+st.count+' 条':'失败 · '+st.error):loading?'检查中':'尚未成功采集'}</span></div><p>{s.language==='zh'?'中文 · ':''}{s.kind?s.kind+' · ':''}{s.description}</p>{st?.latestPublishedAt&&<p>本源最新原文：{new Date(st.latestPublishedAt).toLocaleString('zh-CN',{timeZone:'Asia/Shanghai',hour12:false})}（北京时间）</p>}{st&&<small>检查时间：{new Date(st.checkedAt).toLocaleString('zh-CN',{timeZone:'Asia/Shanghai',hour12:false})}</small>}<a href={s.url} target="_blank" rel="noreferrer">打开订阅源<ExternalLink size={13}/></a></div>;})}</div><p className="muted">返回页面 15 分钟内复用本机缓存；同日服务端缓存最多一小时，跨日或手动刷新重新采集。失败时保留本设备上次成功结果，并显示真实采集时间；若没有缓存，显示空状态；历史精选只在“全部 / 资料库”中展示。不提供逐秒行情，不将旧文章重新标为今日发布。</p><button className="primary-button" onClick={()=>void refresh(true)} disabled={loading}>{loading?'正在检查…':'重新检查来源'}</button></DialogContent></Dialog>
 <Dialog open={!!company} onOpenChange={o=>!o&&setCompany(null)}><DialogContent className="atlas-dialog">{company&&<><DialogHeader><DialogTitle>{company.name} <span className="muted">{company.code}</span></DialogTitle><DialogDescription>{company.area}</DialogDescription></DialogHeader><h3>技术观察</h3><p>{company.tech}</p><div className="company-stats"><div><span>{company.period}</span><strong>{company.revenue}</strong></div><div><span>{company.name==='ABB'?'Operational EBITA 利润率':'毛利率'}</span><strong>{company.margin}</strong></div></div><p className="financial-note">{company.note}</p><p className="muted">财务数字为注明报告期的核验快照。新财报请查官方披露；本站不会根据新闻标题自动推算或覆盖指标。</p><h3>本次采集的相关动态</h3><div className="news-list">{(data?.items||[]).filter(n=>{const keys:Record<string,string[]>= {'NVIDIA':['nvidia','英伟达'],'Google / Alphabet':['google','alphabet','谷歌','gemini','deepmind'],'Microsoft':['microsoft','微软','phi-'],'阿里巴巴 / 通义':['阿里','通义','qwen'],'Hugging Face':['hugging face','smol'],'宇树科技':['宇树','unitree'],'优必选':['优必选','ubtech'],'Vertiv':['vertiv','维谛'],'Serve Robotics':['serve robotics']};return (keys[company.name]||[company.name]).some(k=>n.title.toLowerCase().includes(k.toLowerCase()));}).filter((n,i,arr)=>arr.findIndex(x=>x.url===n.url)===i).slice(0,4).map(newsRow)}</div><p className="muted">仅显示本次成功采集并匹配企业名称的动态；未显示不代表企业没有更新。</p><div className="dialog-links"><a className="primary-button" href={company.url} target="_blank" rel="noreferrer">核查原始资料<ArrowUpRight size={16}/></a><a className="text-button" href={company.ir} target="_blank" rel="noreferrer">官方披露入口<ArrowUpRight size={16}/></a></div></>}</DialogContent></Dialog></>;
}
function Calculator({domain}:{domain:Domain}){
 const [power,setPower]=useState('1000');const [pue,setPue]=useState('1.3');const [price,setPrice]=useState('0.7');const [trials,setTrials]=useState('100');const [success,setSuccess]=useState('90');
 const p=Number(power),u=Number(pue),c=Number(price),n=Number(trials),s=Number(success);const valid=power!==''&&pue!==''&&price!==''&&p>0&&u>=1&&c>=0&&[p,u,c].every(Number.isFinite);const rValid=trials!==''&&success!==''&&Number.isInteger(n)&&Number.isInteger(s)&&n>0&&s>=0&&s<=n;const rate=s/n;const z=1.96;const center=(rate+z*z/(2*n))/(1+z*z/n);const half=z*Math.sqrt(rate*(1-rate)/n+z*z/(4*n*n))/(1+z*z/n);
 return <section className="calculator"><div><span className="eyebrow">INTERACTIVE NOTEBOOK / 学习计算器</span><h2>{domain==='aidc'?'把参数代入，检查你的估算。':'成功率，也需要置信区间。'}</h2><p>{domain==='aidc'?'总电费 = 平均 IT 功率 × PUE × 8,760 h × 电价。假设全年恒定，不含需量费、峰谷差异和税费。':'输入固定测试集的试验与成功次数，查看 Wilson 95% 置信区间。假设各次试验独立同分布；不代表安全认证。'}</p></div><div className="calculator-controls">{domain==='aidc'?<><label>平均 IT 功率 / kW<Input type="number" min="1" value={power} onChange={e=>setPower(e.target.value)}/></label><label>PUE / ≥ 1<Input type="number" min="1" step="0.01" value={pue} onChange={e=>setPue(e.target.value)}/></label><label>电价 / 元·kWh⁻¹<Input type="number" min="0" step="0.01" value={price} onChange={e=>setPrice(e.target.value)}/></label><output aria-live="polite"><span>估算年度电费</span><strong>{valid?(p*u*8760*c/10000).toFixed(2)+' 万元':'请输入有效参数'}</strong></output></>:<><label>总试验次数<Input type="number" min="1" step="1" value={trials} onChange={e=>setTrials(e.target.value)}/></label><label>成功次数<Input type="number" min="0" step="1" value={success} onChange={e=>setSuccess(e.target.value)}/></label><output aria-live="polite"><span>{rValid?'成功率 '+(rate*100).toFixed(1)+'% · 95% 置信区间':'次数需为整数且成功次数≤总次数'}</span><strong>{rValid?(Math.max(0,center-half)*100).toFixed(1)+'% — '+(Math.min(1,center+half)*100).toFixed(1)+'%':'请检查输入'}</strong></output></>}</div></section>
}
