'use client';
import {useState} from 'react';
import {sourceCatalog} from '@/lib/source-catalog';
import {domainNames,frameworks,evidenceTopics} from '@/lib/research-framework';
import type {Domain,News} from '@/lib/content';
import type {UpdateResult} from '@/hooks/use-updates';
import type {Indicators} from '@/lib/indicators';
export function ResearchCenter({domain,items,updates,indicators,metricLoading,onMetrics,onExport,exporting}:{domain:Domain;items:News[];updates:UpdateResult|null;indicators:Indicators|null;metricLoading:boolean;onMetrics:()=>void;onExport:()=>void;exporting:boolean}){
 const [sourceQuery,setSourceQuery]=useState(''),[sourceGroup,setSourceGroup]=useState('全部');
 const relevant=sourceCatalog.filter(s=>s.domains.includes(domain));
 const visible=relevant.filter(s=>(sourceGroup==='全部'||s.group===sourceGroup)&&JSON.stringify(s).toLowerCase().includes(sourceQuery.toLowerCase()));
 const counts=Object.entries(items.reduce<Record<string,number>>((a,n)=>(a[n.type]=(a[n.type]||0)+1,a),{}));const max=Math.max(1,...counts.map(x=>x[1]));const f=frameworks[domain];
 return <section className="research-center"><div className="research-intro"><div><span className="eyebrow">RESEARCH DESK / 证据与判断</span><h2>{domainNames[domain]} · 技术与产业研报</h2><p>{f.thesis}</p></div><button className="primary-button" onClick={onExport} disabled={exporting}>{exporting?'正在汇编…':'一键导出研报'}</button></div>
 <div className="research-kpis"><div><b>{items.length}</b><span>当前时间窗线索</span></div><div><b>{items.filter(n=>n.region==='cn').length}</b><span>中国相关线索</span></div><div><b>{relevant.length}</b><span>相关来源目录项</span></div><div><b>{items.filter(n=>n.stale).length}</b><span>旧缓存条目</span></div></div>
 <p className="muted">研报按本页领域、时间窗和区域汇编技术与产业全类型，包含分析框架、数据表、原文索引与来源台账。导出为离线 HTML，打开后可打印或保存 PDF。条目数量是采集覆盖，不是行业市场份额。</p>
 <div className="research-framework">{f.questions.map((q,i)=><article key={q.title}><span className="eyebrow">研究主线 0{i+1}</span><h3>{q.title}</h3><p>{q.logic}</p><b>跟踪指标</b><p>{q.metrics}</p><small>{q.verify}</small></article>)}</div>
 <div className="research-themes"><h3>本期研究线索</h3><p>按标题与摘要关键词归类，每条可归入多个主题；用于发现待核查证据，不代表阅读全文后的结论。</p><div className="research-framework">{evidenceTopics(domain,items).map(t=><article key={t.title}><span className="eyebrow">{t.count} 条相关线索</span><h3>{t.title}</h3>{t.latest.length?t.latest.map(n=><p key={n.url}><a href={n.url} target="_blank" rel="noreferrer">{n.title}</a><small>{n.source} · {new Date(n.date).toLocaleDateString('zh-CN',{timeZone:'Asia/Shanghai'})}{n.stale?' · 旧缓存':''}</small></p>):<p>该主题暂无匹配线索。</p>}</article>)}</div></div><div className="evidence-bars"><h3>本期证据分布</h3>{counts.length?counts.map(([k,n])=><div key={k}><span>{k}</span><i style={{width:n/max*100+'%'}}/><b>{n}</b></div>):<p>等待成功采集；暂无可用于统计的条目。</p>}</div>
 <section className="live-metrics"><div className="section-heading"><h2>宏观背景与模型服务数据</h2><button onClick={onMetrics} disabled={metricLoading}>{metricLoading?'正在获取…':'刷新数据'}</button></div><p>经济数据按原始观察期展示；模型报价为服务目录，不代表能力排名。{indicators?'采集于 '+new Date(indicators.checkedAt).toLocaleString('zh-CN',{timeZone:'Asia/Shanghai'}):'进入研报中心时自动获取。'}</p>
 <div className="live-metric-grid">{indicators?.indicators.map(x=><article key={x.id}><span>{x.name}</span><strong>{x.value.toFixed(2)}<small>{x.unit}</small></strong><b>观察期 {x.period}</b><p>{x.note}</p>{x.history&&<details><summary>历史数值</summary><table className="data-table"><thead><tr><th>观察期</th><th>{x.unit}</th></tr></thead><tbody>{x.history.map(h=><tr key={h.period}><td>{h.period}</td><td>{h.value.toFixed(2)}</td></tr>)}</tbody></table></details>}<a href={x.url} target="_blank" rel="noreferrer">{x.source}</a></article>)}</div>
 {indicators?.statuses.map(s=><p className={s.ok?'muted':'feed-error'} key={s.name}>{s.name} · {s.ok?'已连接':s.error||'暂不可用'}</p>)}
 {domain==='ml'&&!!indicators?.models.length&&<><h3>模型目录近期条目</h3><p>USD / 百万 token；输入输出分别计费，未计缓存折扣、税费和实际路由差异。按目录创建时间选取，<a href="https://openrouter.ai/rankings" target="_blank" rel="noreferrer">使用量榜单请查看原站</a>。</p><div className="table-wrap"><table className="data-table"><thead><tr><th>模型</th><th>上下文 tokens</th><th>输入价</th><th>输出价</th></tr></thead><tbody>{indicators.models.map(m=><tr key={m.id}><td><a href={m.url} target="_blank" rel="noreferrer">{m.name}</a></td><td>{m.context.toLocaleString()}</td><td>{m.input===null?'未提供':m.input.toFixed(3)}</td><td>{m.output===null?'未提供':m.output.toFixed(3)}</td></tr>)}</tbody></table></div></>}
 </section>
 <section className="source-library"><div className="section-heading"><h2>专业来源库</h2><span>已核对 {sourceCatalog.length} 项 · 当前领域 {relevant.length} 项</span></div><p>数据接口、公开索引、开发工具和参考资料分别标注。公开索引通过机构域名发现标题与链接，不代表已读取全部报告或付费全文。</p><label className="catalog-search">搜索机构或研究主题<input type="search" value={sourceQuery} onChange={e=>setSourceQuery(e.target.value)} placeholder="例如 IDC、世界模型、利率…"/></label><div className="filter-row">{['全部',...new Set(relevant.map(s=>s.group))].map(g=><button key={g} className={sourceGroup===g?'selected':''} onClick={()=>setSourceGroup(g)}>{g}</button>)}</div>
 <div className="source-catalog">{visible.map(s=>{const status=updates?.statuses.find(x=>x.name==='研报索引 · '+s.feedGroup);return <article key={s.id}><span className="eyebrow">{s.group} / {s.mode}</span><h3>{s.name}</h3><p>{s.purpose}</p><small>{s.note}</small>{s.feedGroup&&<p className="catalog-status">索引组：{s.feedGroup} · {status?(status.ok?'已检查 · 组内 '+status.count+' 条':status.error):'等待检查'}<small>组内结果可能来自其他机构；并非该网站单独命中数。</small></p>}{s.url?<a href={s.url} target="_blank" rel="noreferrer">访问原始资料</a>:<span className="unresolved">待补充书签原网址</span>}</article>})}</div>{!visible.length&&<p className="empty">没有匹配来源，请调整筛选。</p>}</section></section>;
}
