import type {Domain,News} from './content';
import type {UpdateResult} from '@/hooks/use-updates';
import type {Indicators} from './indicators';
import {sourceCatalog} from './source-catalog';
import {domainNames,frameworks,evidenceTopics} from './research-framework';
export type ReportInput={domain:Domain;items:News[];updates:UpdateResult|null;indicators:Indicators|null;region:string;age:string;loading:boolean};
const esc=(s:unknown)=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]!));
const safe=(s:string)=>/^https?:\/\//i.test(s)?esc(s):'#';
const stamp=(s:string)=>new Date(s).toLocaleString('zh-CN',{timeZone:'Asia/Shanghai',hour12:false});
export function reportStats(items:News[]){const counts=new Map<string,number>();for(const n of items)counts.set(n.type,(counts.get(n.type)||0)+1);return [...counts].sort((a,b)=>b[1]-a[1]);}
export function createReport(input:ReportInput){
 const {domain,updates,indicators}=input;const now=new Date().toISOString(),name=domainNames[domain],f=frameworks[domain];
 const seen=new Set<string>();const items=input.items.filter(n=>n.domain===domain&&!seen.has(n.url)&&Boolean(seen.add(n.url))).sort((a,b)=>Date.parse(b.date)-Date.parse(a.date));
 const tech=items.filter(n=>['技术研究','研究论文','产品发布'].includes(n.type)),industry=items.filter(n=>!tech.includes(n));
 const catalog=sourceCatalog.filter(s=>s.domains.includes(domain));const counts=reportStats(items),max=Math.max(1,...counts.map(x=>x[1]));
 const row=(n:News)=>`<tr><td>${esc(stamp(n.date))}</td><td><a href="${safe(n.url)}">${esc(n.title)}</a><small>${esc(n.source)} · ${esc(n.sourceKind||'订阅来源')}${n.stale?' · 旧缓存':''}</small></td><td>${esc(n.type)}</td></tr>`;
 const table=(list:News[])=>list.length?`<table><thead><tr><th>原文时间（北京）</th><th>公开标题与原文</th><th>类型</th></tr></thead><tbody>${list.map(row).join('')}</tbody></table>`:'<p>该时间窗暂无成功采集的对应条目，不代表行业没有进展。</p>';
 const metric=(indicators?.indicators||[]).map(x=>`<tr><td>${esc(x.name)}</td><td>${esc(x.value.toFixed(2))} ${esc(x.unit)}</td><td>${esc(x.period)}</td><td><a href="${safe(x.url)}">${esc(x.source)}</a><small>${esc(x.note)}</small></td></tr>`).join('');
 const observations=items.length?`本期已采集 ${items.length} 条去重线索，技术类 ${tech.length} 条，产业及财务类 ${industry.length} 条，来自 ${new Set(items.map(n=>n.source)).size} 个标注发布来源。其中 ${items.filter(n=>n.region==='cn').length} 条匹配中国相关关键词，${items.filter(n=>n.stale).length} 条来自旧缓存。最近原文为 ${stamp(items[0].date)}。这些数量描述本站样本覆盖，不是行业市场份额或增长率。`:'本期未取得可用资讯样本。以下保留研究框架和来源清单，不生成缺乏依据的趋势结论。';
 return `<!doctype html><html lang="zh-CN"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>${esc(name)}技术与产业研报 · ATLAS</title><style>
 *{box-sizing:border-box}body{font-family:"Noto Sans CJK SC","PingFang SC","Microsoft YaHei",sans-serif;color:#16312f;background:#edf2f1;margin:0;line-height:1.8}.paper{max-width:1060px;margin:30px auto;padding:56px;background:white}h1{font-size:36px;line-height:1.35}h2{margin-top:42px;border-bottom:2px solid #14776e;padding-bottom:8px}h3{font-size:20px}p{font-size:16px}.meta,small{color:#536a67}small{display:block;font-size:12px}a{color:#116d66;overflow-wrap:anywhere}table{border-collapse:collapse;width:100%;font-size:14px;margin:18px 0;table-layout:fixed}td,th{padding:10px;border:1px solid #c9d9d4;text-align:left;vertical-align:top;overflow-wrap:anywhere}th{background:#e9f2ef}th:first-child{width:20%}.lead{background:#eaf4f0;padding:22px;border-left:4px solid #14776e}.bar{display:grid;grid-template-columns:100px 1fr 50px;align-items:center;gap:14px;margin:10px 0}.bar i{background:#14776e;height:18px;display:block}.toolbar{max-width:1060px;margin:24px auto}button{padding:12px 20px;background:#14776e;color:white;border:0;cursor:pointer;font-size:16px}.source-row{break-inside:avoid;border-bottom:1px solid #ddd;padding:10px 0}@page{size:A4;margin:18mm}@media print{body{background:white}.paper{padding:0;margin:0;max-width:none}.toolbar{display:none}h1{font-size:28px}h2,h3{break-after:avoid}tr{break-inside:avoid}thead{display:table-header-group}p{orphans:3;widows:3}a{color:#173d36}table{font-size:11px}small{font-size:10px}}
 </style></head><body><div class="toolbar"><button onclick="window.print()">打印 / 保存为 PDF</button></div><main class="paper"><p class="meta">ALU / 知域 ATLAS · 研究资料汇编</p><h1>${esc(name)}<br>技术与产业研报</h1><p class="meta">生成时间 ${esc(stamp(now))}（北京时间）<br>范围：${input.region==='cn'?'中国相关':'全球'} · ${input.age==='archive'?'已采集资料库':'近 '+esc(input.age)+' 天'} · 技术与产业全类型<br>新闻采集时间：${updates?esc(stamp(updates.checkedAt)):'尚未采集'}${input.loading?' · 刷新尚未完成，本文件为部分结果快照':''}</p>
 <div class="lead"><b>研究主线</b><p>${esc(f.thesis)}</p></div>
 <h2>一、执行摘要与证据覆盖</h2><p>${esc(observations)}</p><p>本报告依据公开标题、链接和结构化数据自动汇编。下文分析框架为本站方法说明；标题索引未经逐篇全文核验，不据此自动推算业绩、市场规模或投资回报。</p>
 ${counts.map(([label,count])=>`<div class="bar"><span>${esc(label)}</span><i style="width:${count/max*100}%"></i><b>${count} 条</b></div>`).join('')}<small>图：本站当前筛选的条目类型分布；同一事件的多家报道仍可能重复计数。</small>
 <h3>本期研究线索</h3><p>按标题与摘要关键词归类，主题可重叠；代表性原文需进一步核查。</p>${evidenceTopics(domain,items).map(t=>`<h3>${esc(t.title)} · ${t.count} 条</h3>${t.latest.length?`<ul>${t.latest.map(n=>`<li><a href="${safe(n.url)}">${esc(n.title)}</a><small>${esc(n.source)} · ${esc(stamp(n.date))}${n.stale?' · 旧缓存':''}</small></li>`).join('')}</ul>`:'<p>本期暂无匹配线索。</p>'}`).join('')}<h2>二、技术路线与产业传导</h2>${f.questions.map((q,i)=>`<section><h3>${i+1}. ${esc(q.title)}</h3><p>${esc(q.logic)}</p><p><b>建议跟踪：</b>${esc(q.metrics)}</p><p><b>证据核对：</b>${esc(q.verify)}</p></section>`).join('')}
 <h2>三、宏观背景与模型服务数据</h2><p>宏观指标用于背景分析，与领域市场规模不等同。采集时间：${indicators?esc(stamp(indicators.checkedAt)):'本次未加载结构化数据'}。</p>${metric?`<table><thead><tr><th>指标</th><th>值 / 单位</th><th>观察期</th><th>来源与口径</th></tr></thead><tbody>${metric}</tbody></table>`:'<p>本次暂无已加载指标；缺失值不补估。</p>'}
 ${domain==='ml'&&indicators?.models.length?`<h3>模型目录近期条目与报价</h3><p>按目录创建时间选取，非能力或调用量排名；单位 USD / 百万 token，输入与输出分别计费，未计税费、缓存折扣和实际路由差异。</p><table><thead><tr><th>模型</th><th>上下文 tokens</th><th>输入价</th><th>输出价</th></tr></thead><tbody>${indicators.models.map(m=>`<tr><td><a href="${safe(m.url)}">${esc(m.name)}</a></td><td>${m.context}</td><td>${m.input===null?'未提供':m.input.toFixed(3)}</td><td>${m.output===null?'未提供':m.output.toFixed(3)}</td></tr>`).join('')}</tbody></table>`:''}
 <h2>四、技术与产品证据索引（${tech.length}）</h2>${table(tech)}
 <h2>五、产业、资本与财务证据索引（${industry.length}）</h2>${table(industry)}
 <h2>六、后续研究清单</h2><ol><li>对重要进展打开原文，记录作者、日期、实验条件和证据等级。</li><li>将市场预测与实测分开；统一年份、币种、收入与交付口径再比较。</li><li>用企业原始披露核验订单、收入和现金流，避免上下游重复累计。</li><li>对来源失败、缺失观察期和历史缓存补充核查；不将缺失视为零。</li></ol>
 <h2>七、来源台账与更新边界</h2><p>已核对来源目录共 ${sourceCatalog.length} 项，以下列出与本领域相关的 ${catalog.length} 项。公开索引仅表示已配置域名检索，不代表全部报告已抓取；付费全文与付费行情不纳入正文。</p>${catalog.map(s=>`<div class="source-row"><b>${esc(s.name)}</b> · ${esc(s.group)} · ${esc(s.mode)}<br>${esc(s.purpose)}<small>${esc(s.note)}</small>${s.url?`<a href="${safe(s.url)}">${esc(s.url)}</a>`:'<small>等待补充原始网址</small>'}</div>`).join('')}
 <h3>本次采集健康状态</h3>${(updates?.statuses||[]).map(s=>`<p>${esc(s.name)}：${s.ok?'成功 · '+s.count+' 条':esc(s.error||'失败')}<small>检查 ${esc(stamp(s.checkedAt))}</small></p>`).join('')}${(indicators?.statuses||[]).map(s=>`<p>${esc(s.name)}：${s.ok?'数据接口成功':esc(s.error||'失败')}</p>`).join('')}<p class="meta">生成文件为当前数据快照，离线打开不会自行更新。返回网站刷新后可再次导出。</p></main></body></html>`;
}
export function downloadReport(input:ReportInput){const html=createReport(input);const url=URL.createObjectURL(new Blob([html],{type:'text/html;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download='ATLAS_'+input.domain.toUpperCase()+'_Research_'+new Date().toISOString().slice(0,10)+'.html';document.body.appendChild(a);a.click();a.remove();return {url,filename:a.download};}
