import {concepts} from '@/lib/concepts';
import {articles} from '@/lib/content';
import {deep} from '@/lib/deep-content';
import {newDeep} from '@/lib/new-content';
import {LearningDiagram} from '@/components/learning-diagram';
import {WorldResearch} from '@/components/world-research';
import {notFound} from 'next/navigation';
import {ArrowLeft,BookOpen,CheckCircle2} from 'lucide-react';
export async function generateMetadata({params}:{params:Promise<{id:string}>}){const {id}=await params;const a=articles.find(a=>a.id===id);return {title:a?a.title+' · 知域 ATLAS':'未找到文章'};}
export default async function ArticlePage({params}:{params:Promise<{id:string}>}){
 const {id}=await params;const a=articles.find(a=>a.id===id);if(!a)notFound();const detail=deep[id]||newDeep[id];const terms=concepts.filter(c=>c.article===id);
 return <><header className="read-header"><a className="brand" href="/"><span className="brand-mark">A</span><b>知域<span> ATLAS</span></b></a><a href={'/?domain='+a.domain+'&view=library'}><ArrowLeft size={16}/> 返回知识手册</a></header><main className="reading"><div className="eyebrow">{{aidc:'AIDC 智算基础设施',robot:'ROBOTICS 具身智能',ml:'MACHINE LEARNING 机器学习'}[a.domain]} / {a.category}</div><h1>{a.title}</h1><p className="read-intro">{a.summary}</p><div className="read-meta"><BookOpen size={16}/>{a.level} · 约 {a.minutes} 分钟<span>正文修订：2026-10-01</span></div><div className="reading-grid"><article>{terms.map(c=><section className="concept-detail" id={c.slug} key={c.slug}><span className="eyebrow">百科词条 / {c.alias}</span><h2>{c.term}</h2><p className="concept-definition">{c.definition}</p><h3>工作原理：从输入到结果</h3><p>{c.mechanism}</p><h3>具体例子与推导</h3><p className="worked-example">{c.example}</p><h3>适用边界</h3><p>{c.boundary}</p></section>)}<LearningDiagram nodes={detail.nodes} title={detail.title}/>{a.sections.map((s,i)=><section id={'section-'+i} key={s.title}><span className="section-number">0{i+1}</span><h2>{s.title}</h2><p>{s.text}</p></section>)}<section id="model"><span className="section-number">06</span><h2>数学模型与可复算示例</h2><div className="formula-box">{detail.formula}</div><p className="worked-example"><b>代入与解释</b>{detail.example}</p><p className="muted">以上数值用于教学；除明确注明的研究与市场数据外，均为假设工况。使用时统一单位并检查适用条件。</p></section><section id="mistakes"><h2>常见误区</h2><p>{detail.pitfalls}</p></section><section className="check-section" id="checks"><h2>工程核对清单</h2>{a.checks.map(t=><p key={t}><CheckCircle2 size={18}/>{t}</p>)}</section>{id.startsWith('w')&&<WorldResearch/>}<section><h2>在综合案例中理解本专题</h2><a className="case-inline" href={'/case-study#'+(a.domain==='aidc'?'infrastructure':a.domain==='robot'?'robot':'intelligence')}>液冷智算机房的机器人巡检闭环：从 1 MW 负载到异常复核与工单</a><p>将知识放入同一套输入、计算、执行和验收过程，观察参数变化怎样传递到其他系统。</p></section><section><h2>延伸阅读与资料来源</h2><p>继续查阅技术细节、接口和完整推导，可打开下列原始资料；站内词条用于串联核心概念。</p><a className="source-link" href={a.source} target="_blank" rel="noreferrer">{a.sourceName}</a><p className="muted">本文为原创学习讲解，链接供核查与进阶阅读。涉及设备型号、标准与接口时，以项目适用版本为准。工程例题不替代正式设计。</p></section></article><aside className="read-toc"><span className="eyebrow">本文目录</span>{terms.map(c=><a href={"#"+c.slug} key={c.slug}>词条 · {c.term}</a>)}{a.sections.map((s,i)=><a key={s.title} href={'#section-'+i}>0{i+1}　{s.title}</a>)}<a href="#model">06　模型与算例</a><a href="#mistakes">07　常见误区</a><a href="#checks">08　核对清单</a><hr/><span className="eyebrow">继续学习</span>{articles.filter(x=>x.domain===a.domain&&x.id!==a.id).slice(a.domain==='robot'?12:0,a.domain==='robot'?17:4).map(x=><a key={x.id} href={'/read/'+x.id}>{x.title}</a>)}</aside></div></main><footer className="footer"><span>知域 ATLAS</span>专业知识 · 可靠来源 · 持续探索</footer></>;
}
